### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by maxbeatty** [MindscapeHQ/raygun4js#110]
We'd like to install raygun4js through npm. You look to have everything you need to publish this (package.json, git tags, npm account) so should just be `npm publish`

**Comment by jholster** [comment]
+1 for this. It's nowadays common to use npm (with tools like browserify) also for "client-side" libraries.

**Comment by fundead** [comment]
Hi guys,

This has been a long-standing request, and up until now we've held off on it due to a naming collision in npm with Raygun4node, (which is in the package "raygun"). It's looking like publishing to npm in addition to bower will have the least friction despite this, due to browserify enabling the use of require() for npm modules as you mention (e.g without having to resort to browserify-shim or similar).

We're going to talk this over and going to plan it should be published to npm in the near term. Will keep you posted.

**Comment by maxbeatty** [comment]
IMO you should publish as "raygun4js" to match bower (like jquery, requirejs, backbone, moment, accounting). You could also use [a scoped package](https://docs.npmjs.com/getting-started/scoped-packages) but that requires consumers to use npm greater than 2.7.0. In the meantime, we've just been pointing at tags in our `package.json` using the GitHub shorthand:

```json
"raygun4js": "MindscapeHQ/raygun4js#v1.18.2",
```

**Comment by fundead** [comment]
Pleased to announce that's exactly what we've done - this is now released as "raygun4js" on npm and should be usable in browserify. Feel free to open up another issue if you have troubles.

Package docs available at https://www.npmjs.com/package/raygun4js - we'll be adding instructions for npm to the Raygun docs soon.
