### ISSUE TITLE
Errors rejected due to account processing limits get saved and sent again

### ISSUE THREAD

**Issue by lee-houghton** [MindscapeHQ/raygun4js#116]
We noticed this one when dealing with the result of #115.

If an error is rejected due to our raygun account's processing usage being maxed out, the API returns HTTP status code 429. Raygun4JS sees this as a network error (not 400 or 403), and thus saves the error to send later.

https://github.com/MindscapeHQ/raygun4js/blob/58c315977a26d7eb1f1c97b294180be9da48020d/src/raygun.js#L707

I think this behaviour is probably unwanted in most cases. It means that as soon as our next billing period starts, we'll probably be slammed with thousands of errors that were saved to localStorage, and go over our limit again in less than a day - this month we went over our limit in less than 2 hours. If you're going over your processing limit, you're probably more interested in having a more recent snapshot of errors than in older ones.

I'm proposing not saving offline requests that resulted in HTTP 429. Does this sound like a reasonable change to you? If so I'll send a pull request.

**Comment by fundead** [comment]
Thanks for spotting this case - indeed your analysis sounds like the desired behavior and the provider should not be saving errors that were rejected due to the processing limit. As clientside errors are usually representative and result in many instances there shouldn't be much of an issue in dropping them; as you note it is more valuable to receive fresh errors when the processing limit is reset than what was persisted in localstorage since the plan was capped.

Your proposal sounds entirely reasonable, and if you wanted to put together a PR this would be appreciated and we can work on getting a release out promptly.

**Comment by lee-houghton** [comment]
Sorry, fat fingers! Thanks for your quick response.  It's obviously up to you, but FYI, we're not in a rush for an official release as we can use my github fork for now ☺
