### ISSUE TITLE
Serve gzipped content from cdn.raygun.io

### ISSUE THREAD

**Issue by bryanrsmith** [MindscapeHQ/raygun4js#161]
The documentation for this library suggests loading it from cdn.raygun.io, which isn't gzipping the response (probably because the cloudfront distribution is backed by an S3 bucket). gzip would reduce the transfer size from ~30kb to ~10kb.

**Comment by fundead** [comment]
You're correct in that the CDN is S3 -> Cloudfront and therefore doesn't support auto gzipping currently. Unfortunately we can't manually gzip the artifacts due to the case where the client doesn't support it. The plan was to monitor and enable it once Amazon implement this, but it looks like this might be a while out if ever. As such it's on our roadmap to investigate alternate CDN providers next year.

Note that functionality the Cache-Control header is set so the script is cached in the client, so only the first request incurs the network penalty. We do however note that many site perf tools report resources that aren't gzipped for clients that can accept that as an error (correctly), so as above we do intend to implement this by moving the CDN in the future.

**Comment by fundead** [comment]
Just an update on this one, fortunately near the end of last month Amazon happened to implement this, and thus we enabled it. Scripts from the CDN are now automatically delivered gzipped where the client supports it.

**Comment by bryanrsmith** [comment]
Excellent! Thanks for following up.
