### ISSUE TITLE
tracekit/ is stale

### ISSUE THREAD

**Issue by mvines** [MindscapeHQ/raygun4js#164]
Tracekit 0.1.0 has been embedded here, while the upstream has moved on to 0.3.1.

**Comment by fundead** [comment]
Thanks for bringing this up, we had to vendor Tracekit initially as it remained unmaintained for a significant amount of time a few years ago, which therefore resulted in our own fixes applied to our fork. As such merging in the latest upstream changes is a nontrivial amount of work and necessitates significant QA due to outside work which we will look at next year.

**Comment by mvines** [comment]
You may want to consider switching over to https://www.npmjs.com/package/stacktrace-parser as well

**Comment by fundead** [comment]
At a glance that's missing a WinJS regex which we had to build, and a couple of Gecko improvements, but we'll keep an eye on it.
