### ISSUE TITLE
API V2 not available via bower

### ISSUE THREAD

**Issue by jmorrice** [MindscapeHQ/raygun4js#169]
Hi,

Any reason the V2 API isn't available through the bower package?

Thanks!

**Comment by fundead** [comment]
Hi,

The V2 API can be used when Raygun4JS is served from your site's domain (e.g via bundling or otherwise) by using Bower or one of the other package managers, as opposed to the CDN. The scope creep is becoming significant with this provider due to the rather large array of options one has when designing a web site/application, so we wanted to keep the setup instructions manageable for the V2 release. I'm open to adding this to the main docs if it becomes a popular request from the community.

To load Raygun4JS asynchronously from your own domain (thereby enabling the V2 API) where the script is available, include the snippet as per Step 1 of the CDN instructions, but change the URI in the last line (second last string parameter) to point at the location of the script:

```
<script type="text/javascript">
    !function(a,b,c,d,e,f,g,h){a.RaygunObject=e,a[e]=a[e]||function(){
    (a[e].o=a[e].o||[]).push(arguments)},f=b.createElement(c),g=b.getElementsByTagName(c)[0],
    f.async=1,f.src=d,g.parentNode.insertBefore(f,g),h=a.onerror,a.onerror=function(b,c,d,f,g){
    h&&h(b,c,d,f,g),g||(g=new Error(b)),a[e].q=a[e].q||[],a[e].q.push({
    e:g})}}(window,document,"script","//www.mydomain.com/scripts/raygun.min.js","rg4js");
</script>
```

Then proceed with Step 2 as per the docs. This will async load the script and make it available as the rg4js global object. Currently this requires the raygun.min.js file to remain unbundled from other application scripts however if a Cache-Control header is set on this file (as it should be) it will be cached in the client and no request overhead will be incurred.
