### ISSUE TITLE
Using rg4js 'options' at a later stage

### ISSUE THREAD

**Issue by itayadler** [MindscapeHQ/raygun4js#170]
It seems that using the `rg4js` function at a later stage for modifying for example `ignoreAjaxError` doesn't seem to work. Is this an issue or simply it's undocumented how it's supposed to be used?

**Comment by fundead** [comment]
`rg4js` currently is strictly a loader used to bootstrap the provider asynchronously with config options once it's loaded. I've updated the documentation at https://github.com/MindscapeHQ/raygun4js#differences-between-raygun4js-v1-and-v2 in order to highlight how the Raygun object should be used after load. In this case you'll want to call `Raygun.init(apiKey, options)` in the onLoad callback as ignoreAjaxError is set in the options payload.

We're debating enhancing the rg4js object to proxy calls through but this necessitates snippet and API changes and we're very wary of breaking changes here due to the scope of the effects, so a solid amount of QA will be needed before anything changes here.
