### ISSUE TITLE
rg4js should support all methods even once raygun.js has loaded

### ISSUE THREAD

**Issue by jbedard** [MindscapeHQ/raygun4js#192]
Today once raygun.js [loads](https://github.com/MindscapeHQ/raygun4js/blob/v2.3.4/src/raygun.loader.js#L87) many rg4js methods no longer work (noConflict, apiKey, enablePulse, options, attach).

In my specific use case I don't know the `apiKey` until post-load, but `onLoadHandler` only gets invoked once on initial load. There might also be a race condition here between setting these options and raygun.js loading and reading the options.

I'd think if rg4js supported these properties (noConflict, ...) then the full `onLoadHandler` could be dropped? That would lose things like `{ handler: 'From Raygun4JS snippet global error handler' }` and `window.onerror = null` though (the second of which I think is part of this bug, but it would be an API change).

**Comment by fundead** [comment]
Regarding apiKey, noConflict, enablePulse and attach (which is a legacy alias for enableCrashReporting), these are top-level initialization options that are required for the provider to begin execution, as they control the high-level code paths that are executed based on the desired features. For instance, with noConflict, this renames the global variable if there's another already defined, so it doesn't make sense to want to call this again after the script has been parsed and executed. There's a potentially valid case for `options` to be called again, however the majority of these are global environment options which don't usually change at runtime, e.g `apiEndpoint`, `excludedHostNames` etc. If you could let me know more details about your use case and why you'd want to re-set them I can look at supporting this.

With regards to the apiKey only being available after onLoad, can you also provide more details about why this is not known until after pageLoad? As the Raygun API key is changed infrequently and can be provided as a variable read from configuration, potentially varying only based on server environment, the expected scenario is to inject it with server-side templating so it is present in the HTML immediately on document load. The architecture of the provider is to expect at minimum the API key and one of `enableCrashReporting`/`enablePulse` to be set; these govern what the provider should do immediately after page load (e.g send all pending errors that were caught during the load, attach the global handler or not, start Pulse event recording and transmission).

If the API key isn't immediately present, these can't happen, and due to the many and varied browser environments this provider is expected to run under, there's benefit in keeping this logic as simple and reliable as possible. Delaying the execution of the provider after page load due to the API key not being present makes it error prone, for instance, if the API key isn't ever populated then errors and Pulse data would be lost forever, potentially masking critical bugs.

**Comment by jbedard** [comment]
The API key is configurable in a server config file which I don't want to duplicate (or generate) on the client. JS fetches this data (along with other config stuff) right after loading but that may or may not be after raygun has loaded - it's a race condition between raygun.js and app.js+ajax-call (which raygun almost always wins).

My workaround would be to remove the `<script>` insertion from the raygun snippet and do it manually after the API key is known. I just need #191 before I can do that.

But... if `rg4js("apiKey", "...")` + `rg4js("attach", ...)` worked like every other command then I'd think most of `onLoadHandler` would no longer be necessary? Same with noConflict and I assume enablePulse. I'd think it would be simpler and less code that way. The only issue I see is supporting the existing `window.onerror = null` case, not sure how that could still be supported with my proposal...

**Comment by fundead** [comment]
If I'm understanding your scenario correctly, you are just loading the API key via an XHR request as opposed to writing it via templating to the static HTML document, and due to this being an extra request it may arrive at some time after page load (unbounded with poor network conditions), resulting in a potential race condition, and if/when the config data does arrive at which point you want the browser to execute the raygun.min.js logic/re-initialize itself with new config variables?

The main issue I see with this delayed approach is that it adds extra moving parts into an already unreliable process (due to the aformentioned network conditions and wildly differing browser implementations of an already complex HTML/asset loading and execution model). The best approach when using a library that catches errors and timings is to go for the simplest and most reliable approach.

In this case it is placing the API key and startup config variables in the HTML document so that they're guaranteed to be present when the script is downloaded asynchronously - no document, no app, no variables, and if raygun4js downloads it is guaranteed to run and transmit any app code errors that occur (which is the critical requirement).

The proposed alternative approach appears to perform the exact same behaviour, but requires a rewrite of the core provider logic for no additional gain in functionality. In particular for the API key, there is no duplication by rendering it into the document, as it needs to be passed to the client either way - delivering it via XHR just adds overhead, delays execution and creates the race condition which you've noticed. The main benefit of the current async snippet + config variables in a script tag is that this race condition is removed.

If the issue is obfuscation of the API key, we haven't seen a problem with it being placed in the document, and delivering it via XHR still sends it to the client where it can be read by anyone. This same approach is industry standard and is used by others e.g Google Analytics etc. An alternative would be to render these into minified JS referenced in a script tag in the HEAD which would arguably be less discoverable than an XHR which appears in the Dev Tools Network tab.

On that point, a Raygun API key is considered public and non-secure, in the event that it is stolen, a new one can be generated in Application Settings in the web app, and if it's used as a denial of service (which we've never seen) we have several mechanisms in place to prevent this and will quite happily reset your usage manually for the month.

Finally, the proposed changes to drop the onloadhandler would necessitate an additional API approach and incompatibilities/breaking changes with legacy code - with the change from V1 to V2 we've found people find this confusing so introducing a third scenario would just increase the confusion. For the options in question e.g `apiKey` `attach` `noConflict` these are initialization-time options and make sense for them to be required to boot the provider. If there's a benefit to be gained we're more than happy to look at this however, we'd just need more details about the requirements first.

Hope this helps clear up some of the issues here, again we'd be happy to look at this further if it will result in a significant benefit to the usage of the provider, however I need to be able to justify the time involved to refactor the initialization logic so if you can give me more information on your scenario this can be looked at in future.

Regards,

Callum Gavin
Raygun Limited

**Comment by jbedard** [comment]
I think if #191 is fixed I can download the raygun js file myself after the API key is known, while still collecting errors before then (via `window.error` + `rg4js('send', ...)`). I just thought a more generic solution would also be useful to others.

The API key is already public enough, that's not the issue. The issue is that my html file is not generated dynamically right now, and I don't want to :) I'd think there are more use cases for this though. What if I want the HTML served from a CDN but the raygun API key is on an application server? (I'm not sure if that is realistic, so ignore me if not!).

I understand that API changes are tough so I'd understand not wanting to drop/change `onloadhandler`. Was just an idea that would be ideal for my specific situation.

**Comment by fundead** [comment]
You can indeed trigger the download of raygun.min.js yourself manually after the API key is known, and as #191 is now fixed this should cover this edge case. We've been refactoring this provider moving towards a more pure implementation however browsers still don't quite provide the async semantics we need - hopefully when ES6 modules are fully supported by the evergreen browsers we can revisit this.
