### ISSUE TITLE
Invoking 'send()' on a sync XHR is deprecated

### ISSUE THREAD

**Issue by nijikokun** [MindscapeHQ/raygun4js#193]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Invoking 'send()' on a sync XHR during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details.

**Comment by fundead** [comment]
Is this an automated report? If the provider is configured correctly all XHRs requests have the async flag set disregarding the non-applicable Tracekit code paths. If you have noticed this please provide more details on where and how you saw the synchronous XHR warning.

**Comment by xt0rted** [comment]
I just got the following in my console
> Use of XMLHttpRequest with the synchronous flag set to true is deprecated due to its impact on user-perceived site performance.

It was in reference to https://github.com/MindscapeHQ/raygun4js/blob/645f55aa3f6b0b9e36e1bdec1835feedd22d216c/dist/raygun.js#L344

**Comment by nijikokun** [comment]
It is not an automated report @fundead, it is a warning and soon to be error within this library.

**Comment by fundead** [comment]
The underlying issue here is https://github.com/csnover/TraceKit/issues/13. I have made a note to update the dependency and disable this functionality which will avoid the warning as on the surface it looks like we don't need this behavior.

**Comment by coryd** [comment]
It's past September 2016, so we're still seeing this warning and not seeing the error reported in Raygun.
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

It seems to work in Firefox 49.0.1 on OS X, but not in Chrome 53.0.2785.143 (64-bit)

**Comment by fundead** [comment]
Hi Cory,

Can you provide more details about where and how you saw this issue (e.g the calling code the threw the original exception, a link to a page that exhibits the behavior if the page is public, a repro snippet etc)? Also, are you using another dependency which also uses/bundles Tracekit internally? Currently we aren't receiving reports of this occurring consistently, thus this appears to be a spurious warning that appears under some circumstances. As noted above we've disabled the code path that would perform the sync request, but we'd like to find out why this warning is being raised and fix it. Any futher details you can provide will assist us in this.

**Comment by coryd** [comment]
I can't share the specific code snippet because it's within an authenticated application. However, I can supply the pseudo code that sets up up the situation. 

We are not reporting a JavaScript error, instead we are using raygun in this scenario to report a particular case we want to look into.


`if (thingsAreNotTheSame) {
	Raygun.send(new Error("Things aren't the same buddy!"), { data1: data1, data2: data2 });
}`

The warning is raised from https://cdn.raygun.io/raygun4js/raygun.js at line 344.

We are using Angular 1.5.8 but we have no dependencies on Tracekit.

We have configured raygun in it's most basic form following the instructions outlined here:

https://github.com/MindscapeHQ/raygun4js

with the following settings

`<script type="text/javascript">
rg4js('apiKey', 'key');
rg4js('enableCrashReporting', true);        
rg4js('options', { ignore3rdPartyErrors: true });
rg4js('setUser', {
                identifier: 'id',
                isAnonymous: false,
                email: 'email',
                firstName: 'first',
                fullName: 'full'
            });
</script>`

Please let me know if there are further details I can provide that will help. Thank you for you time.

**Comment by fundead** [comment]
Update on this one: the latest v2.4.2 release which is just about to go out removes the offending LOC in question so Chrome should no longer detect and raise the warning.

**Comment by coryd** [comment]
Awesome. Thank you.

**Comment by sitefinitysteve** [comment]
I'm seeing this still (or again?)
Raygun4js - v2.8.6 - 2018-03-06
![image](https://user-images.githubusercontent.com/1542376/38202089-849edd80-3668-11e8-8666-9be0e8875180.png)
