### ISSUE TITLE
Not getting sourcemap info in Edge

### ISSUE THREAD

**Issue by xt0rted** [MindscapeHQ/raygun4js#197]
I'm not sure if this is a configuration issue on my end, or an issue with Edge, but this is the stack trace for the latest error I got.

``` js
at e line null, column null (null:null)
at b line null, column null (null:null)
at dispatch line null, column null (null:null)
at function (e) line null, column null (null:null)
at trigger line null, column null (null:null)
at i line null, column null (null:null)
at function () line null, column null (null:null)
```

There's also a comment on the error page that says:

> Source maps couldn't be processed as the browser hasn't sent column numbers.

The only thing I know for sure is the page this happened on, but I can't tell from where or what caused it.

Is this a result of not setting `ignoreAjaxAbort` or `ignoreAjaxError`? My calls on this page are returning a `409` when there's an error but I'm not sure if these were sent as a result of that.

**Comment by fundead** [comment]
In the latest v2.5.0 we've updated the regexes to the latest version provided by the vendor lib so that stacktrace should now be parsed correctly and provide the line/column numbers. If this was a breaking change introduced by Edge since the last update we may need to provide additional regex tweaks - if you or anyone else notices this issue in future please leave a comment and we'll take another look.

**Comment by xt0rted** [comment]
My code is loading raygun4js with `//cdn.raygun.io/raygun4js/raygun.min.js` which is currently showing v2.4.3 - 2016-12-06. Can I test v2.5 with the cdn?

**Comment by fundead** [comment]
We leave the deployment of the unversioned CDN root artifact a few days due to its immediate effect upon customers, as a smoke test for stability. It's available now from the versioned route at //cdn.raygun.io/raygun4js/2.5.0/raygun.min.js which you can reference from the snippet.
