### ISSUE TITLE
Unhandled error not caught or sent to Raygun in React-Native

### ISSUE THREAD

**Issue by janyk** [MindscapeHQ/raygun4js#217]
The following error is not handled or caught:
`throw new Error('Some error')` 

Is there more than just the below setup I need to do or is this is a bug/unsupported feature?

```
To automatically catch and send unhandled errors, you can attach the automatic window.onerror handler callback:

// V2
rg4js('enableCrashReporting', true);
```

Environment info:
```
react-native": "0.41.0",
raygun4js": "^2.6.0-SNAPSHOT.5"
```

**Comment by fundead** [comment]
Hi again, can you answer the following questions so I can get to the bottom of this:

Where in the app lifecycle is this error thrown (e.g in a child component, a class function, a render function)?
Are you using iOS or Android?
Are you running it in the simulator or on a device? If in the simulator, is it running in debug (red box with the bundle console open) or release mode?
Does it work in some of these situations but not others?

**Comment by janyk** [comment]
Have tried it in most life cycle hooks (render method, componentWillUpdate etc..), have tried it in class functions, the constructor, above creation of the class, in various middle ware. In all these cases manual sending of an error works using:
```
 rg4js('send',
       {
         error: 'some error',
         customData: [{ foo: 'bar' }]
       });
```

but throwing like `throw new Error('Some error')` is not handled.

I have tried with and without setting a user.

The issue is reproducible on both Android and iOS.
Running it on the simulator for both Android and iOS, in debug mode, see attached screen shots

![screen shot 2017-03-17 at 11 09 13 am](https://cloud.githubusercontent.com/assets/13877025/24020724/4f75d97a-0b02-11e7-8da1-22146fa1b3ce.png)
![screen shot 2017-03-17 at 11 09 19 am](https://cloud.githubusercontent.com/assets/13877025/24020725/4f767d08-0b02-11e7-812f-1722dc8383f9.png)

**Comment by fundead** [comment]
Right, that is by design as uncaught errors aren't automatically sent in debug mode due to https://github.com/MindscapeHQ/raygun4js/blob/react-native-compat/src/raygun.js#L149 - this is the approach used as standard in a couple of our other providers e.g Rails and by some competitors for React Native.

The intention here is that the error and stacktrace is provided by the red box, thus avoiding mixing dev errors with real production errors without having to worry about config transforming the API key out of the box. To see unhandled errors sent, run your application in release mode (without the bundle console window open).

**Comment by janyk** [comment]
Ah, of course, that makes a lot of sense.
Thanks so much 👍
