### ISSUE TITLE
Typescript definitions are for V1

### ISSUE THREAD

**Issue by RobinClowers** [MindscapeHQ/raygun4js#250]
When I import the library from the npm package, I get the V2 api, but the typescript definitions are for V1. I see there is an interface definition for `RaygunV2`, but it's not exported, so I'm not sure how I can use it. Does the package actually include both versions of the API? It seems like the package should be split, or at least there should be different exports for the each api version.

**Comment by BenjaminHarding** [comment]
The package does include both versions of the API. 

To use the RaygunV2 with TS you will need to declare your `rg4js` variable and assign its type, which I do agree isn't the best approach at this point. 

```ts
import { RaygunV2 } from 'raygun4js';
declare var rg4js: RaygunV2;
```

The reasons for this is because the variable is actually configurable in the snippet and so isn't as static, although I don't believe anyone actually changes it. The V2 API also only works when you use the snippet (or at least did at writing). 

Perhaps we can look at updating this definition at some point if anyone has recommendations.

**Comment by RobinClowers** [comment]
Thanks for the quick response. When I `import { RaygunV2 } from 'raygun4js';` I get `Module ''raygun4js'' has no exported member 'RaygunV2'.`

**Comment by BenjaminHarding** [comment]
Oops, I believe I got the example wrong and you don't need to import it. Just `declare var rg4js: RaygunV2;` should suffice

**Comment by RobinClowers** [comment]
Hmm, that might work if I use the async loader script. Maybe I'll try that.

**Comment by RobinClowers** [comment]
For the record, it does seem like I only get the V1 api through the npm package, using the async script load plus the type definition from npm worked great through. Thanks for your help!
