### ISSUE TITLE
React Native and RUM

### ISSUE THREAD

**Issue by dentuzhik** [MindscapeHQ/raygun4js#310]
When trying to enable pulse in a project using react native, this line fails, because readCookie tries to access the document.
https://github.com/MindscapeHQ/raygun4js/blob/fe24038dcf88541ba5b7447627f76269ee1e0015/src/raygun.rum.js#L208

At the same time error reporting initialises correctly, because it uses `Raygun.Utilities.readCookie`, which has a check for React Native environment. 

Is it expected behaviour and pulse is just not supposed to work for RN, or is it just a bug?

**Comment by brentron9000** [comment]
@UberMouse It appears this is still an issue?

**Comment by UberMouse** [comment]
While this isn't intentional, RUM in Raygun4JS is not designed in a way that would work with React Native. This would be something we work on eventually but it will most likely end up being its own provider rather an update to Raygun4JS.

So I'm going to close this issue for now as I don't think it's likely we will add react native support to RUM in Raygun4JS. If that changes at some point in the future I'll reopen this issue.

**Comment by dentuzhik** [comment]
> So I'm going to close this issue for now as I don't think it's likely we will add react native support to RUM in Raygun4JS. If that changes at some point in the future I'll reopen this issue.

Considering how trivial it to fix this crash, wouldn't it make more sense to actually do it? While I understand that RUM will not work at least it will not make consumer spend an hour debugging next time and disabling it through env check (our app is using same code and reporting for both web & native).

Early guard condition here with a console warning would be sufficient enough to notify consumer that some parts are just not working. Wdyt?

**Comment by brentron9000** [comment]
@UberMouse thank you for the quick response! I thought that React Native supported RUM because of this section in the [docs](https://raygun.com/documentation/language-guides/javascript/crash-reporting/react-native/):

`// Put any other rg4js() options you want to set here`

I didn't realize that was actually under the `Crash Reporting` section and not the `Real User Monitoring` section. My bad there.

**Comment by UberMouse** [comment]
> Early guard condition here with a console warning would be sufficient enough to notify consumer that some parts are just not working. Wdyt?

That makes sense @dentuzhik, I'll change it to not initialise RUM in React Native in the next release.

**Comment by dentuzhik** [comment]
Thank you 🥇
