### ISSUE TITLE
Script error in prompt.js

### ISSUE THREAD

**Issue by szare** [MindscapeHQ/raygun4js#326]
I'm receiving the following error related to the raygun4js:

![Screen Shot 2019-06-04 at 3 22 30 pm](https://user-images.githubusercontent.com/15211997/58853282-06b60f80-86dd-11e9-8284-11372df70093.png)

**Comment by UberMouse** [comment]
Hi @szare,

That error is not actually related to Raygun4JS. What we are doing is creating a new `Error` object at that point that wraps the provided message because one was not provided to the `window.onerror` handler.

When you construct an `Error` object the stacktrace is grabbed which is why the stacktrace is pointing at Raygun4JS.

Regards,
Taylor

**Comment by szare** [comment]
Hi @UberMouse,

Thanks for your quick response.
I'll check it again.

Thanks,
Salman
