### ISSUE TITLE
a security question related to api key exposed.

### ISSUE THREAD

**Issue by bugknr** [MindscapeHQ/raygun4js#421]
Hii can anyone explain me this peace of code
<script type="text/javascript">
    rg4js('apiKey', 'paste_your_api_key_here');
    rg4js('enableCrashReporting', true);
</script>

i not sure but i think this peace of code i have to write in client side.
what happen if a malicious user read the source code and copy my apikey and try to generate huge number of error traffic to increase my bill.
i always heard apikey should be in server side not client.

**Comment by NoahDumba** [comment]
> Hii can anyone explain me this peace of code
> <script type="text/javascript"> rg4js('apiKey', 'paste_your_api_key_here'); rg4js('enableCrashReporting', true); </script>
> 
> i not sure but i think this peace of code i have to write in client side.
> what happen if a malicious user read the source code and copy my apikey and try to generate huge number of error traffic to increase my bill.
> i always heard apikey should be in server side not client.

I am also concerned about this. How would one go about injecting the API key into the html file instead of hard coding it?

**Comment by bugknr** [comment]
actually
I generated almost thousand of fake logs in less than 30 sec.
Also i reported this to a hackerone private program but they said its public and close my report.

**Comment by CmdrKeen** [comment]
Hi folks,

This is by design. It's the same way any JavaScript would work (including Google Analytics!).

Because you track from the front end, you have to base something from the user. As you note, you can never fully trust anything coming from the client (we'll put by the wayside the industries interest in loading as much business logic to the user in JS for the moment ;-) )

Even if you built a special end point, that only attached the API key to send off to Raygun from the server side - how would you protect that end point from being called by a bad actor? The simple answer is, you wouldn't really.

Having said this, 

1. You're right to query it.
2. We do provide tools to rotate the key in the situations of it being stolen/abused
3. We've never actually had a customer have that happen to them
4. There's not really a benefit for an attacker in using the end point (while we are primarily a self-service product, we do provide support and would, of course, mitigate any issues related to on-demand charges in the case of abuse - one of our company values is 'don't f--k the customer' for a good reason!).

I hope that helps, but this is unfortunately what happens when you need something in the client side, and effectively all JavaScript services use this mechanism because it's what is available.

HackerOne is right to close it because you could submit this to every JavaScript based service out there. You could send fake GA data, you could send Intercom messages, you can do whatever you want. Never trust the client because you don't control it! :-)

I hope that helps, and I welcome suggestions that would mitigate this risk.

John-Daniel Trask

**Comment by bugknr** [comment]
I am not sure but i think you are charging per query not per month.
Attacker can use this to send fake logs and customer have to pay you for that log if you are providing per query service.
And one more thing you said that user can alter the query.
If you give me permission then 
I want to check for xss , sql injection like vulnerability because you told that attacker can change the query.

**Comment by CmdrKeen** [comment]
We do charge that way, but it's not being exploited, and even if it was an accident by yourself, we'd have that discussion.

This applies the same to any 'pay for what you use' service. What if somebody starts DDOSing your site hosted by AWS? If you can scale, it will cost you. But you can talk to them, and work together to solve it. That's what I'm suggesting you do if this happens to you.

As noted, you are welcome to share how you'd solve this issue, as it's occurring for any JavaScript service you use, and any 'pay for what you use' service. If you become aware that you're seeing data that isn't yours, you should let us know immediately.

The user can alter the API key if they were determined. But they can do that for every other service too - like Google Analytics, Intercom, Clicky, etc - every single JavaScript package works this way. This is why it won't be accepted as a bug by any security team, it's the price you pay for running code on an untrusted machine - the client. Given our JS script is just for tracking client performance and errors, it needs to be JavaScript (the same issue does not exist for our vast support for backend code, it's because folks do need to monitor the front end that it's ending up there too).

I'm going to close this issue as there's no solution to the issue, and it's not a Raygun specific one.
