### ISSUE TITLE
Support for AMD/require.js

### ISSUE THREAD

**Issue by carltierney** [MindscapeHQ/raygun4js#80]
Being able to manage raygun4js with require.js when working with cross browser development or HTML5/javascript based mobile phone applications.

**Comment by maxbeatty** [comment]
We use raygun4js in our Require.js project like this:

```js
require.config({
  paths: {
    raygun: 'path/to/raygun4js/dist/raygun.vanilla.min'
  }
})

require([
  'raygun' // no export
], function() {
  Raygun.init(...)
})
```

**Comment by RichiCoder1** [comment]
That's not a full solution. You'd need to throw in a shim in the config with an export of 'Raygun', and a dependency of 'jquery' for the non vanilla config.

That being said, proper AMD support, or even UMD support, would be fantastic.

**Comment by chiplay** [comment]
:+1: (webpack user)

**Comment by alexdrel** [comment]
:+1: (another webpack user)
Current npm package without CommonJS support is a sad joke.

**Comment by alanjames1987** [comment]
+1

**Comment by bjornbos** [comment]
+1

**Comment by detj** [comment]
UMD support please.

I also noticed the current version exposes following properties in the global namespace.

```
Raygun
raygunFactory
raygunJsUrlFactory
raygunRumFactory
TraceKit
```

Apart from `Raygun`, I don't think the rest of the properties are designed to be used by the consumers of the plugin. If that is so, is there any other reason for exposing these as globals?

**Comment by dmitry-zaets** [comment]
Any update so far?

**Comment by fundead** [comment]
No update on this currently, as the provider would initially require a refactor away from its custom module implementation, as require.js/clientside modules weren't popularized when this provider was conceived. This is on our internal backlog and will be completed when time is available.

Secondly, due to the need to load the library asynchronously and as early as possible, the snippet/CDN V2.0 approach provides better data for both Crash Reporting and Pulse compared to what a module dependency loading library could provide, thus this will remain the recommended approach.

Finally, due to the upcoming ES6 module format we most likely won't settle on AMD but a forward-compatible approach that will support the future JS standard and won't result in unnecessary churn.

We will also be looking at tidying up those properties in global scope.

**Comment by dmitry-zaets** [comment]
Thanks for the information!

**Comment by detj** [comment]
Wonderful, thanks.
